In [1]:
from mxnet import nd

In [2]:
x=nd.array([1,2,3,4])

In [8]:
x**2


[ 1.  4.  9. 16.]
<NDArray 4 @cpu(0)>

In [14]:
x2=nd.random.normal(0,1,shape=(3,4))

In [16]:
x2


[[ 0.7740038   1.0434405   1.1839255   1.8917114 ]
 [-1.2347414  -1.771029   -0.45138445  0.57938355]
 [-1.856082   -1.9768796  -0.20801921  0.2444218 ]]
<NDArray 3x4 @cpu(0)>

In [17]:
mean=x2.mean(axis=0);mean


[-0.77227324 -0.90148944  0.17484061  0.9051723 ]
<NDArray 4 @cpu(0)>

In [18]:
x3=nd.array([[1,2,3,4],
             [2,3,4,5],
             [3,4,5,6]]);x3


[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
<NDArray 3x4 @cpu(0)>

In [23]:
x3.shape

(3, 4)

In [26]:
mean = x3.mean(axis=0);mean


[2. 3. 4. 5.]
<NDArray 4 @cpu(0)>

In [30]:
((x3-mean)**2).mean(axis=0)


[0.6666667 0.6666667 0.6666667 0.6666667]
<NDArray 4 @cpu(0)>

In [36]:
x4=nd.arange(3*2*3*4);x4


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.]
<NDArray 72 @cpu(0)>

In [38]:
x4_1=x4.reshape((3,2,3,4));x4_1


[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]]

  [[12. 13. 14. 15.]
   [16. 17. 18. 19.]
   [20. 21. 22. 23.]]]


 [[[24. 25. 26. 27.]
   [28. 29. 30. 31.]
   [32. 33. 34. 35.]]

  [[36. 37. 38. 39.]
   [40. 41. 42. 43.]
   [44. 45. 46. 47.]]]


 [[[48. 49. 50. 51.]
   [52. 53. 54. 55.]
   [56. 57. 58. 59.]]

  [[60. 61. 62. 63.]
   [64. 65. 66. 67.]
   [68. 69. 70. 71.]]]]
<NDArray 3x2x3x4 @cpu(0)>

In [41]:
mean_x4_1=x4_1.mean(axis=(0,2,3),keepdims=1);mean_x4_1


[[[[29.5]]

  [[41.5]]]]
<NDArray 1x2x1x1 @cpu(0)>

In [44]:
print(12-41.5)
x4_1

-29.5



[[[[ 0.  1.  2.  3.]
   [ 4.  5.  6.  7.]
   [ 8.  9. 10. 11.]]

  [[12. 13. 14. 15.]
   [16. 17. 18. 19.]
   [20. 21. 22. 23.]]]


 [[[24. 25. 26. 27.]
   [28. 29. 30. 31.]
   [32. 33. 34. 35.]]

  [[36. 37. 38. 39.]
   [40. 41. 42. 43.]
   [44. 45. 46. 47.]]]


 [[[48. 49. 50. 51.]
   [52. 53. 54. 55.]
   [56. 57. 58. 59.]]

  [[60. 61. 62. 63.]
   [64. 65. 66. 67.]
   [68. 69. 70. 71.]]]]
<NDArray 3x2x3x4 @cpu(0)>

In [48]:
variance_x4=((x4_1-mean_x4_1)**2).mean(axis=(0,2,3),keepdims=True)

In [49]:
x_hat=(x4_1-mean_x4_1)/nd.sqrt(variance_x4+1e-5);x_hat


[[[[-1.4825867  -1.4323295  -1.3820723  -1.3318152 ]
   [-1.281558   -1.2313008  -1.1810436  -1.1307865 ]
   [-1.0805293  -1.0302721  -0.980015   -0.9297578 ]]

  [[-1.4825867  -1.4323295  -1.3820723  -1.3318152 ]
   [-1.281558   -1.2313008  -1.1810436  -1.1307865 ]
   [-1.0805293  -1.0302721  -0.980015   -0.9297578 ]]]


 [[[-0.27641448 -0.2261573  -0.17590012 -0.12564294]
   [-0.07538576 -0.02512859  0.02512859  0.07538576]
   [ 0.12564294  0.17590012  0.2261573   0.27641448]]

  [[-0.27641448 -0.2261573  -0.17590012 -0.12564294]
   [-0.07538576 -0.02512859  0.02512859  0.07538576]
   [ 0.12564294  0.17590012  0.2261573   0.27641448]]]


 [[[ 0.9297578   0.980015    1.0302721   1.0805293 ]
   [ 1.1307865   1.1810436   1.2313008   1.281558  ]
   [ 1.3318152   1.3820723   1.4323295   1.4825867 ]]

  [[ 0.9297578   0.980015    1.0302721   1.0805293 ]
   [ 1.1307865   1.1810436   1.2313008   1.281558  ]
   [ 1.3318152   1.3820723   1.4323295   1.4825867 ]]]]
<NDArray 3x2x3x4 @cpu(0)>

In [50]:
gamma=nd.array([1,1])

In [51]:
beta=nd.array([0,0])

In [56]:
gamma.reshape(mean_x4_1.shape)*x_hat+beta.reshape(mean_x4_1.shape)


[[[[-1.4825867  -1.4323295  -1.3820723  -1.3318152 ]
   [-1.281558   -1.2313008  -1.1810436  -1.1307865 ]
   [-1.0805293  -1.0302721  -0.980015   -0.9297578 ]]

  [[-1.4825867  -1.4323295  -1.3820723  -1.3318152 ]
   [-1.281558   -1.2313008  -1.1810436  -1.1307865 ]
   [-1.0805293  -1.0302721  -0.980015   -0.9297578 ]]]


 [[[-0.27641448 -0.2261573  -0.17590012 -0.12564294]
   [-0.07538576 -0.02512859  0.02512859  0.07538576]
   [ 0.12564294  0.17590012  0.2261573   0.27641448]]

  [[-0.27641448 -0.2261573  -0.17590012 -0.12564294]
   [-0.07538576 -0.02512859  0.02512859  0.07538576]
   [ 0.12564294  0.17590012  0.2261573   0.27641448]]]


 [[[ 0.9297578   0.980015    1.0302721   1.0805293 ]
   [ 1.1307865   1.1810436   1.2313008   1.281558  ]
   [ 1.3318152   1.3820723   1.4323295   1.4825867 ]]

  [[ 0.9297578   0.980015    1.0302721   1.0805293 ]
   [ 1.1307865   1.1810436   1.2313008   1.281558  ]
   [ 1.3318152   1.3820723   1.4323295   1.4825867 ]]]]
<NDArray 3x2x3x4 @cpu(0)>